name: Deploy via git-ftp
on: push:
  branches:
    - master
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - property:  npm i && npm run build
        run: cd htdocs && npm i && npm run build